#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run formatting and linting on staged files
echo '🏗️ Styling, testing and building your project before committing'

# Check Prettier standards
npm run format ||
(
    echo '❌ Prettier Check Failed. Run npm run format, add changes and try commit again';
    false;
)

# Check ESLint Standards
npm run lint ||
(
    echo '❌ ESLint Check Failed. Make the required changes listed above, add changes and try commit again';
    false;
)

# Run lint-staged
npx lint-staged
